export const CRITERIA_NAME = [
	"Chuẩn đầu ra, yêu cầu và nội dung môn học được giảng viên giới thiệu trong buổi học đầu tiên và thường xuyên nhắc lại trong các buổi học tiếp theo",
	"Phòng học/thí nghiệm và trang thiết bị đáp ứng yêu cầu giảng dạy và học tập.",
	"Giáo trình, bài giảng và tài liệu phục vụ môn học được cung cấp đầy đủ và cập nhật trên hệ thống Moodle",
	"Giảng viên hướng dẫn Anh/Chị phương pháp học tập chủ động và tạo động cơ học tập suốt đời",
	"Giảng viên trình bày các vấn đề trong môn học mang tính cập nhật, chuẩn xác và có liên hệ thực tiễn",
	"Phương pháp giảng dạy của giảng viên giúp Anh/Chị hiểu được và vận dụng được kiến thức",
	"Giảng viên có khả năng truyền đạt tốt",
	"Giảng viên tận tâm, nhiệt tình",
	"Giảng viên sử dụng giờ lên lớp hiệu quả",
	"Giảng viên giảng dạy tuân thủ theo đề cương môn học",
	"Giảng viên đảm bảo giờ lên lớp",
	"Giảng viên sử dụng thiết bị, đồ dùng dạy học hợp lý, hiệu quả",
	"Giảng viên sử dụng các công cụ/phần mềm (hệ thống Moodle) để thảo luận và hỗ trợ Anh/Chị trong quá trình học tập",
	"Giảng viên đánh giá đúng, công bằng kết quả học tập của Anh/Chị",
	"Nội dung kiểm tra/thi tổng hợp được kiến thức/kỹ năng của môn học",
	"Kết thúc môn học, Anh/Chị được trang bị kiến thức và kỹ năng đáp ứng chuẩn đầu ra",
	"Mức độ hài lòng của Anh/Chị về chất lượng giảng dạy môn học",
	"Kết quả học tập được công bố kịp thời giúp Sinh viên điều chỉnh hoạt động học tập",
	"Giảng viên sử dụng nhiều hình thức đánh giá để ghi nhận kết quả học tập của người học",
	"Kết quả kiểm tra - đánh giá phản ảnh đúng và khách quan năng lực của của Anh/Chị",
	"Nội dung môn học được Giảng viên truyền tải chuẩn xác, cập nhật và có liên hệ thực tiễn",
	"Giảng viên sử dụng phương tiện dạy học hợp lý, hiệu quả",
];
